##
## EPITECH PROJECT, 2017
## makefile
## File description:
## file
##

all:
	make -C js_tests/addinf
	make -C js_tests/subinf
	make -C js_tests/mulinf
	make -C js_tests/divinf
	make -C js_tests/modinf